<a href="https://colab.research.google.com/github/dpk-a7/Deep-learning/blob/main/simple_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from __future__ import print_function, division
from builtins import range, input
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

In [3]:
T = 8 #sequence length
D = 2 #input dimensionality
M = 3 #hiddenlayer size

In [5]:
X = np.random.randn(1,T,D)
X

array([[[ 1.03163825, -0.71953098],
        [ 0.00853781,  0.7402735 ],
        [-0.20452175, -0.66004121],
        [-1.55782345, -0.07324312],
        [-0.02573443,  0.97291388],
        [-0.95675742,  0.27499966],
        [ 1.6366397 , -1.19509644],
        [-0.39645626, -0.75070355]]])

In [8]:
def lstm1():
  input_ = Input(shape=(T,D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  o,h,c = model.predict(X)
  print("output(o): ",o)
  print("hidden(h): ",h)
  print("cell state(c): ",c)

In [9]:
lstm1()# o is equal to h

output(o):  [[-0.02642967 -0.08177073 -0.00889597]]
hidden(h):  [[-0.02642967 -0.08177073 -0.00889597]]
cell state(c):  [[-0.05651069 -0.16937327 -0.01504447]]


In [11]:
def lstm2():
  input_ = Input(shape=(T,D))
  rnn = LSTM(M, return_state= True, return_sequences=True)
  # rnn = GRU(M, return_state = True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  o,h,c = model.predict(X)
  print("output(o): ",o)
  print("hidden(h): ",h)
  print("cell state(c): ",c)

In [13]:
lstm2() #o is of len 8 and the last index is equal to h

output(o):  [[[ 0.03619287  0.00510833 -0.16600923]
  [-0.07060698 -0.10658424 -0.02851453]
  [ 0.04532725  0.03341681 -0.05812428]
  [ 0.15506193  0.1303978   0.10059753]
  [-0.05105373  0.00120459  0.22447072]
  [-0.04112259  0.03010226  0.21203357]
  [ 0.04071012  0.01738683 -0.00436735]
  [ 0.16055512  0.10387123 -0.03506802]]]
hidden(h):  [[ 0.16055512  0.10387123 -0.03506802]]
cell state(c):  [[ 0.28125465  0.26425835 -0.07813565]]


* h and c represents the final hidden states of the lstm.
* h and c are the hidden state and the cell state at the final time step

In [18]:
def gru1():
  input_ = Input(shape = (T,D))
  rnn = GRU(M, return_state = True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  o,h = model.predict(X)
  print("output(o): ",o)
  print("hidden(h): ",h)

In [19]:
gru1() #o is same as h

output(o):  [[-0.28984827  0.045361    0.17573981]]
hidden(h):  [[-0.28984827  0.045361    0.17573981]]


In [20]:
def gru2():
  input_ = Input(shape = (T,D))
  rnn = GRU(M, return_state = True, return_sequences=True)
  x = rnn(input_)
  model = Model(inputs = input_, outputs = x)
  o,h = model.predict(X)
  print("output(o): ",o)
  print("hidden(h): ",h)

In [21]:
gru2()#o is of len 8 and the last index is equal to h

output(o):  [[[ 0.00467877  0.03199442  0.3707914 ]
  [ 0.27545723 -0.01628624  0.08544643]
  [-0.06234656 -0.0585709   0.14355624]
  [-0.40315416 -0.15214118 -0.41153377]
  [ 0.2347648   0.01053613 -0.42079073]
  [-0.04695862 -0.00293355 -0.52475184]
  [-0.03138866  0.0814103   0.15198553]
  [-0.28519148 -0.00955906  0.11908737]]]
hidden(h):  [[-0.28519148 -0.00955906  0.11908737]]
